worker_processes auto;
events { worker_connections 1024; }

http {
	server {
		listen 80 default_server deferred;
		server_name _;
		return 301 https://tls.cat;
	}

	server {
		listen 443 ssl;
		server_name faketls.com www.faketls.com;

		ssl_certificate     /etc/ssl/certs/faketls.pem;
		ssl_certificate_key /etc/ssl/private/faketls.key;

		# Tight but safe defaults
		ssl_protocols TLSv1.2 TLSv1.3;
		ssl_prefer_server_ciphers on;

		return 301 https://tls.cat;
	}
}
